baseURL = "https://dominikheussen.de/"
languageCode = "en-us"
title = "Dominik Heußen, Team Lead, Software Engineer"
theme = "vncnt-hugo"

[params]
  author = "Dominik Heußen"
  email = "web@dominikheussen.de"
  description = "Dominik Heußen, team lead, software engineer, trivago, hilden, düsseldorf, nettetal"
  bio = "team lead, software engineer  \ndog, car, smart home, tech guy"
  avatar = "img/avatar.jpg"
  favicon = "img/avatar.ico"
  error404 = "There is no such page."

  [params.contact]
    twitter = "https://twitter.com/nikdom1709"
    linkedin = "https://de.linkedin.com/pub/dominik-heußen/40/b26/7a5"
    xing = "https://www.xing.com/profiles/Dominik_Heussen"
    instagram = "https://www.instagram.com/nikdom1709/"
